name: restaurant_app_final
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.2
  flutter_timezone: ^4.1.0
  google_fonts: ^6.2.1
  http: ^1.3.0
  mocktail: ^1.0.4
  test: ^1.25.2
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  shimmer: ^3.0.0
  sqflite: ^2.4.2
  timezone: ^0.9.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
